name: anxeb_flutter
description: Highly scalable mobile Flutter cross-platform library
publish_to: 'none'
version: 2.3.0
homepage: https://github.com/nodrix/anxeb-flutter

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  android_middleware:
    path: plugins/android_middleware
  cupertino_icons: ^1.0.4
  flutter_keyboard_visibility: ^5.2.0
  after_init: ^0.1.2
  flutter_icons: ^1.1.0
  camera: ^0.9.4+19
  image_crop: ^0.4.0
  path: ^1.8.0
  path_provider: ^2.0.9
  ai_barcode: ^3.0.1
  barcode_scan: ^3.0.1
  dio: ^4.0.6
  shared_preferences: ^2.0.13
  sliding_up_panel: ^2.0.0+1
  pull_to_refresh: ^2.0.0
  google_sign_in: ^5.2.4
  oauth1: ^2.0.0
  flutter_facebook_auth: ^4.1.2
  device_info: ^2.0.3
  percent_indicator: ^4.0.0
  another_flushbar: ^1.10.28
  mime: ^1.0.1
  qr_flutter: ^4.0.0
  photo_view: ^0.13.0
  credit_card_validate: ^0.0.3
  file_picker: ^4.5.1
  sign_in_with_apple: ^3.3.0
  firebase_core: ^1.14.0
  firebase_messaging: ^11.2.12
  firebase_analytics: ^9.1.3
  flutter_app_badger: ^1.3.0
  url_launcher: ^6.0.20
  flutter_pdfview: ^1.2.2
  share: ^2.0.4

flutter:
  uses-material-design: true