name: anxeb_flutter
description: Highly scalable mobile Flutter cross-platform library
publish_to: 'none'
version: 2.1.0
author: Nodrix
homepage: https://github.com/nodrix/anxeb-flutter

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  android_middleware:
    path: plugins/android_middleware
  cupertino_icons: ^1.0.3
  flutter_keyboard_visibility: ^5.0.3
  after_init: ^0.1.2
  flutter_icons: ^1.1.0
  camera: ^0.9.3
  image_crop: ^0.4.0
  path: ^1.8.0
  path_provider: ^2.0.4
  barcode_scan: ^3.0.1
  dio: ^4.0.0
  shared_preferences: ^2.0.7
  sliding_up_panel: ^2.0.0+1
  pull_to_refresh: ^2.0.0
  google_sign_in: ^5.1.0
  oauth1: ^2.0.0
  flutter_login_facebook: ^1.1.0
  device_info: ^2.0.2
  percent_indicator: ^3.0.1
  another_flushbar: ^1.10.24
  mime: ^1.0.0
  qr_flutter: ^4.0.0
  photo_view: ^0.12.0
  torch_compat: ^1.0.2
  credit_card_validate: ^0.0.3
  file_picker: ^4.0.3
  sign_in_with_apple: ^3.0.0
  firebase_core: ^1.6.0
  firebase_messaging: ^10.0.7
  firebase_analytics: ^8.3.2
  flutter_app_badger: ^1.3.0
  url_launcher: ^6.0.10
  flutter_pdfview: ^1.2.1
  share: ^2.0.4

flutter:
  uses-material-design: true