name: anxeb_flutter
description: Highly scalable mobile Flutter cross-platform library
publish_to: 'none'
version: 2.6.0
homepage: https://github.com/nodrix/anxeb-flutter

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  android_middleware:
    path: plugins/android_middleware
  cupertino_icons: ^1.0.5
  flutter_keyboard_visibility: ^5.3.0
  after_init: ^0.1.2
  flutter_icons: ^1.1.0
  camera: ^0.10.0+1
  image_crop: ^0.4.1
  path: ^1.8.1
  path_provider: ^2.0.11
  ai_barcode: ^3.2.4
  barcode_scan2: ^4.2.1
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  sliding_up_panel: ^2.0.0+1
  pull_to_refresh_flutter3: ^2.0.1
  google_sign_in: ^5.4.1
  oauth1: ^2.0.0
  flutter_facebook_auth: ^4.4.1
  device_info: ^2.0.3
  percent_indicator: ^4.2.2
  another_flushbar: ^1.10.29
  mime: ^1.0.2
  qr_flutter: ^4.0.0
  photo_view: ^0.14.0
  credit_card_validate: ^0.0.3
  file_picker: ^5.0.1
  sign_in_with_apple: ^4.1.0
  firebase_core: ^1.20.1
  firebase_messaging: ^12.0.2
  firebase_analytics: ^9.3.1
  flutter_app_badger: ^1.4.0
  url_launcher: ^6.1.5
  flutter_pdfview: ^1.2.3
  share: ^2.0.4
  flutter_translate: ^4.0.3
  google_ml_kit: ^0.12.0
  permission_handler: ^10.0.0
  app_settings: 4.1.8
  package_info: ^2.0.2
  in_app_review: ^2.0.4
  easy_mask: ^2.0.1
  bluetooth_print: ^3.0.1

flutter:
  uses-material-design: true